-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: trailing-whitespace
        files: \.(h|m|swift|js|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-merge-conflict
        files: \.(h|m|swift|js|rb|md|py|sh|txt|yaml|yml)$
    -   id: end-of-file-fixer
        files: \.(h|m|swift|js|rb|md|py|sh|txt|yaml|yml)$
